### ISSUE TITLE
The warnings The method getCellType() from the type Cell is deprecated.

### ISSUE THREAD

**Issue by wenJanus** [tobecrazy/SeleniumDemo#2]
https://github.com/tobecrazy/SeleniumDemo/blob/c3fb4a9c146c076c1bd972f62bc98dcf1e9ce47c/src/main/java/com/dbyl/libarary/utils/ReadExcelUtil.java#L48

I use poi-3.17.

**Comment by tobecrazy** [comment]
/**
     * Return the cell type.
     * 
     * Will return {@link CellType} in version 4.0 of POI.
     * For forwards compatibility, do not hard-code cell type literals in your code.
     *
     * @return the cell type
     * @deprecated POI 3.15. Will return a {@link CellType} enum in the future.
     */

**Comment by tobecrazy** [comment]
POI 更新之后把之前的方法Deprecated了，我更新了下。已经是最新的https://github.com/tobecrazy/SeleniumDemo/commit/01c44841069f0caf4573c404def3252624b94956

**Comment by wenJanus** [comment]
@tobecrazy  Thank you for your support!
